//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeperPRO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KeeperEntities : DbContext
    {
        public KeeperEntities()
            : base("name=KeeperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet staffs { get; set; }
        public virtual DbSet sysdiagrams { get; set; }
        public virtual DbSet users_group_visits { get; set; }
        public virtual DbSet users_personal_visits { get; set; }
    }
}
